/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'customerName' : string,
  'status' : AppointmentStatus,
  'staffId' : string,
  'bookedBy' : Principal,
  'date' : Time,
  'email' : string,
  'notes' : string,
  'serviceId' : string,
  'phone' : string,
  'timeSlot' : TimeSlot,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface ContactInfo {
  'instagram' : string,
  'whatsapp' : string,
  'workingHours' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Gallery {
  'id' : string,
  'category' : string,
  'image' : ExternalBlob,
}
export interface Offer {
  'id' : string,
  'title' : string,
  'description' : string,
  'discountPercent' : bigint,
  'validUntil' : Time,
}
export interface Service {
  'id' : string,
  'durationMins' : bigint,
  'name' : string,
  'description' : string,
  'category' : ServiceCategory,
  'priceInr' : bigint,
}
export type ServiceCategory = { 'bridal' : null } |
  { 'color' : null } |
  { 'treatment' : null } |
  { 'haircut' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Staff {
  'id' : string,
  'bio' : string,
  'name' : string,
  'role' : string,
  'photo' : ExternalBlob,
  'specializations' : Array<string>,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TimeSlot { 'startTime' : string, 'endTime' : string }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateGallery' : ActorMethod<[Gallery], undefined>,
  'addOrUpdateOffer' : ActorMethod<[Offer], undefined>,
  'addOrUpdateService' : ActorMethod<[Service], undefined>,
  'addOrUpdateStaff' : ActorMethod<[Staff], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[Appointment], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteAppointment' : ActorMethod<[string], undefined>,
  'deleteGallery' : ActorMethod<[string], undefined>,
  'deleteOffer' : ActorMethod<[string], undefined>,
  'deleteService' : ActorMethod<[string], undefined>,
  'deleteStaff' : ActorMethod<[string], undefined>,
  'getActiveOffers' : ActorMethod<[], Array<Offer>>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAppointmentsByStaff' : ActorMethod<[string], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getGalleryByCategory' : ActorMethod<[string], Array<Gallery>>,
  'getMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getServicesByCategory' : ActorMethod<[ServiceCategory], Array<Service>>,
  'getStaff' : ActorMethod<[], Array<Staff>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAppointmentStatus' : ActorMethod<
    [string, AppointmentStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];